# <font color = 'red'> Dependencias

In [1]:
import pandas as pd

import sys
import os

# Agregar la carpeta calibration_code al path
sys.path.append(os.path.abspath("../../calibration_code"))

# Ahora puedes importar los módulos personalizados
from modelling_tools import plot_histogram, plot_univariate_freq, create_deciles, count_categories_by_decile, calculate_category_proportions
from utils import g
from config import get_data_path, get_code_path
from data_cleaning import check_dataframe_quality

# <font color = 'red'> Carga de Datos

In [2]:
df = pd.read_csv(get_data_path("bivariate_preprocessed_data.csv"))

In [3]:
res = check_dataframe_quality(df)

No missing values found.
No infinite values found.
No duplicate rows found.

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 85 columns):
 #   Column                                              Non-Null Count   Dtype
---  ------                                              --------------   -----
 0   Customer_ID                                         100000 non-null  object
 1   Age                                                 100000 non-null  int64
 2   Annual_Income                                       100000 non-null  float64
 3   Monthly_Inhand_Salary                               100000 non-null  float64
 4   Num_Bank_Accounts                                   100000 non-null  int64
 5   Num_Credit_Card                                     100000 non-null  int64
 6   Interest_Rate                                       100000 non-null  float64
 7   Num_of_Loan                                         100000 non-null  int64
 8   Delay_from_due_date                                 100000 non-null  int64
 9   Num_of_Delayed_Payment                              100000 non-null  int64
 10  Changed_Credit_Limit                                100000 non-null  float64
 11  Num_Credit_Inquiries                                100000 non-null  int64
 12  Credit_Mix                                          100000 non-null  object
 13  Outstanding_Debt                                    100000 non-null  float64
 14  Credit_Utilization_Ratio                            100000 non-null  float64
 15  Credit_History_Age                                  100000 non-null  int64
 16  Total_EMI_per_month                                 100000 non-null  float64
 17  Amount_invested_monthly                             100000 non-null  float64
 18  Monthly_Balance                                     100000 non-null  float64
 19  Credit_Score                                        100000 non-null  int64
 20  Net_Salary_Ratio                                    100000 non-null  float64
 21  Binary_Credit_Score                                 100000 non-null  int64
 22  Occupation_Accountant                               100000 non-null  bool
 23  Occupation_Architect                                100000 non-null  bool
 24  Occupation_Developer                                100000 non-null  bool
 25  Occupation_Doctor                                   100000 non-null  bool
 26  Occupation_Engineer                                 100000 non-null  bool
 27  Occupation_Entrepreneur                             100000 non-null  bool
 28  Occupation_Journalist                               100000 non-null  bool
 29  Occupation_Lawyer                                   100000 non-null  bool
 30  Occupation_Manager                                  100000 non-null  bool
 31  Occupation_Mechanic                                 100000 non-null  bool
 32  Occupation_Media_Manager                            100000 non-null  bool
 33  Occupation_Musician                                 100000 non-null  bool
 34  Occupation_Scientist                                100000 non-null  bool
 35  Occupation_Teacher                                  100000 non-null  bool
 36  Occupation_Writer                                   100000 non-null  bool
 37  Payment_of_Min_Amount_No                            100000 non-null  bool
 38  Payment_of_Min_Amount_Yes                           100000 non-null  bool
 39  Payment_Behaviour_High_spent_Large_value_payments   100000 non-null  bool
 40  Payment_Behaviour_High_spent_Medium_value_payments  100000 non-null  bool
 41  Payment_Behaviour_High_spent_Small_value_payments   100000 non-null  bool
 42  Payment_Behaviour_Low_spent_Large_value_payments    100000 non-null  bool
 43  Payment_Behaviour_Low_spent_Medium_value_payments   100000 non-null  bool
 44  Payment_Behaviour_Low_spent_Small_value_payments    100000 non-null  bool
 45  Last_Loan_1_Auto Loan                               100000 non-null  bool
 46  Last_Loan_1_Credit-Builder Loan                     100000 non-null  bool
 47  Last_Loan_1_Debt Consolidation Loan                 100000 non-null  bool
 48  Last_Loan_1_Home Equity Loan                        100000 non-null  bool
 49  Last_Loan_1_Mortgage Loan                           100000 non-null  bool
 50  Last_Loan_1_No Loan                                 100000 non-null  bool
 51  Last_Loan_1_Not Specified                           100000 non-null  bool
 52  Last_Loan_1_Payday Loan                             100000 non-null  bool
 53  Last_Loan_1_Personal Loan                           100000 non-null  bool
 54  Last_Loan_1_Student Loan                            100000 non-null  bool
 55  Last_Loan_2_Auto Loan                               100000 non-null  bool
 56  Last_Loan_2_Credit-Builder Loan                     100000 non-null  bool
 57  Last_Loan_2_Debt Consolidation Loan                 100000 non-null  bool
 58  Last_Loan_2_Home Equity Loan                        100000 non-null  bool
 59  Last_Loan_2_Mortgage Loan                           100000 non-null  bool
 60  Last_Loan_2_No Loan                                 100000 non-null  bool
 61  Last_Loan_2_Not Specified                           100000 non-null  bool
 62  Last_Loan_2_Payday Loan                             100000 non-null  bool
 63  Last_Loan_2_Personal Loan                           100000 non-null  bool
 64  Last_Loan_2_Student Loan                            100000 non-null  bool
 65  Last_Loan_3_Auto Loan                               100000 non-null  bool
 66  Last_Loan_3_Credit-Builder Loan                     100000 non-null  bool
 67  Last_Loan_3_Debt Consolidation Loan                 100000 non-null  bool
 68  Last_Loan_3_Home Equity Loan                        100000 non-null  bool
 69  Last_Loan_3_Mortgage Loan                           100000 non-null  bool
 70  Last_Loan_3_No Loan                                 100000 non-null  bool
 71  Last_Loan_3_Not Specified                           100000 non-null  bool
 72  Last_Loan_3_Payday Loan                             100000 non-null  bool
 73  Last_Loan_3_Personal Loan                           100000 non-null  bool
 74  Last_Loan_3_Student Loan                            100000 non-null  bool
 75  Last_Loan_4_Auto Loan                               100000 non-null  bool
 76  Last_Loan_4_Credit-Builder Loan                     100000 non-null  bool
 77  Last_Loan_4_Debt Consolidation Loan                 100000 non-null  bool
 78  Last_Loan_4_Home Equity Loan                        100000 non-null  bool
 79  Last_Loan_4_Mortgage Loan                           100000 non-null  bool
 80  Last_Loan_4_No Loan                                 100000 non-null  bool
 81  Last_Loan_4_Not Specified                           100000 non-null  bool
 82  Last_Loan_4_Payday Loan                             100000 non-null  bool
 83  Last_Loan_4_Personal Loan                           100000 non-null  bool
 84  Last_Loan_4_Student Loan                            100000 non-null  bool
dtypes: bool(63), float64(10), int64(10), object(2)
memory usage: 22.8+ MB

# <font color = 'red'> Análisis

In [6]:
df[['Credit_Score', 'Age']]


df_deciles = create_deciles(df, "Age")

display(df_deciles)

category_counts = count_categories_by_decile(df_deciles)

display(category_counts)

category_proportions = calculate_category_proportions(df_deciles)

display(category_proportions)

,Customer_ID,Age,Annual_Income,Monthly_Inhand_Salary,Num_Bank_Accounts,Num_Credit_Card,Interest_Rate,Num_of_Loan,Delay_from_due_date,Num_of_Delayed_Payment,...,Last_Loan_4_Credit-Builder Loan,Last_Loan_4_Debt Consolidation Loan,Last_Loan_4_Home Equity Loan,Last_Loan_4_Mortgage Loan,Last_Loan_4_No Loan,Last_Loan_4_Not Specified,Last_Loan_4_Payday Loan,Last_Loan_4_Personal Loan,Last_Loan_4_Student Loan,Decile
0,CUS_0x98ed,31,22229.060,1672.421667,6,4,5.0,3,10,10,...,False,False,False,False,True,False,False,False,False,4
1,CUS_0x36b4,43,17060.705,1685.725417,8,3,11.0,4,24,8,...,False,True,False,False,False,False,False,False,False,7
2,CUS_0x105b,24,34428.210,2575.017500,2,4,8.0,0,3,12,...,False,False,False,False,True,False,False,False,False,2
3,CUS_0x4c4a,21,12613.920,1155.160000,4,6,13.0,3,14,17,...,False,False,False,False,True,False,False,False,False,1
4,CUS_0x612f,31,34775.160,3048.930000,7,9,25.0,5,20,20,...,False,False,False,True,False,False,False,False,False,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,CUS_0xc52a,46,35032.660,2853.388333,10,6,33.0,7,48,18,...,False,False,False,True,False,False,False,False,False,8
99996,CUS_0x83cc,34,125047.240,10682.603333,2,5,9.0,0,11,4,...,False,False,False,False,True,False,False,False,False,5
99997,CUS_0x6ae6,26,9045.485,644.664842,8,7,20.0,6,52,16,...,False,False,False,False,False,False,False,False,False,2
99998,CUS_0x6f0c,20,53564.880,4207.740000,5,3,13.0,2,6,7,...,False,False,False,False,True,False,False,False,False,1
99999,CUS_0x743f,28,28901.070,2145.422500,4,2,9.0,0,10,6,...,False,False,False,False,True,False,False,False,False,3

Credit_Score     0     1     2
Decile
0             4275  5478  1435
1             2809  5253  3176
2             2330  3982  2457
3             2274  4209  2332
4             3050  5165  3223
5             2245  4131  2440
6             3127  5364  3028
7             1995  4084  2243
8             1663  4318  3974
9                0  3864  6076

Credit_Score         0         1         2
Decile
0             0.382106  0.489632  0.128262
1             0.249956  0.467432  0.282613
2             0.265709  0.454100  0.280192
3             0.257969  0.477482  0.264549
4             0.266655  0.451565  0.281780
5             0.254651  0.468580  0.276770
6             0.271465  0.465665  0.262870
7             0.239726  0.490747  0.269527
8             0.167052  0.433752  0.399196
9             0.000000  0.388732  0.611268

In [ ]:
# POR ACÁ! DEVOLVERME A LA GENERACIÓN DEL DATASET PARA CONVERTIR EN NUMÉRICAS LAS VARIABLES BOOLEANAS
# CONTINUAR EL ANÁLISIS BIVARIADO